"""
Small script to generate many different name-version combinations from Pygin's codebase.
"""

# Names taken from Docker's generator at 
# https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go.
# 
# The list is no longer maintained, and therefore there may be names in here
# that shouldn't be, but this makes reasonable-sounding packages.

NAMES = ['agnesi',
 'albattani',
 'allen',
 'almeida',
 'antonelli',
 'archimedes',
 'ardinghelli',
 'aryabhata',
 'austin',
 'babbage',
 'banach',
 'banzai',
 'bardeen',
 'bartik',
 'bassi',
 'beaver',
 'bell',
 'benz',
 'bhabha',
 'bhaskara',
 'black',
 'blackburn',
 'blackwell',
 'bohr',
 'booth',
 'borg',
 'bose',
 'bouman',
 'boyd',
 'brahmagupta',
 'brattain',
 'brown',
 'buck',
 'burnell',
 'cannon',
 'carson',
 'cartwright',
 'carver',
 'cerf',
 'chandrasekhar',
 'chaplygin',
 'chatelet',
 'chatterjee',
 'chaum',
 'chebyshev',
 'clarke',
 'cohen',
 'colden',
 'cori',
 'cray',
 'curie',
 'curran',
 'darwin',
 'davinci',
 'dewdney',
 'dhawan',
 'diffie',
 'dijkstra',
 'dirac',
 'driscoll',
 'dubinsky',
 'easley',
 'edison',
 'einstein',
 'elbakyan',
 'elgamal',
 'elion',
 'ellis',
 'engelbart',
 'euclid',
 'euler',
 'faraday',
 'feistel',
 'fermat',
 'fermi',
 'feynman',
 'franklin',
 'gagarin',
 'galileo',
 'galois',
 'ganguly',
 'gates',
 'gauss',
 'germain',
 'goldberg',
 'goldstine',
 'goldwasser',
 'golick',
 'goodall',
 'gould',
 'greider',
 'grothendieck',
 'haibt',
 'hamilton',
 'haslett',
 'hawking',
 'heisenberg',
 'hellman',
 'hermann',
 'herschel',
 'hertz',
 'heyrovsky',
 'hodgkin',
 'hofstadter',
 'hoover',
 'hopper',
 'hugle',
 'hypatia',
 'ishizaka',
 'jackson',
 'jang',
 'jemison',
 'jennings',
 'jepsen',
 'johnson',
 'joliot',
 'jones',
 'kalam',
 'kapitsa',
 'kare',
 'keldysh',
 'keller',
 'kepler',
 'khayyam',
 'khorana',
 'kilby',
 'kirch',
 'knuth',
 'kowalevski',
 'lalande',
 'lamarr',
 'lamport',
 'leakey',
 'leavitt',
 'lederberg',
 'lehmann',
 'lewin',
 'lichterman',
 'liskov',
 'lovelace',
 'lumiere',
 'mahavira',
 'margulis',
 'matsumoto',
 'maxwell',
 'mayer',
 'mccarthy',
 'mcclintock',
 'mclaren',
 'mclean',
 'mcnulty',
 'meitner',
 'mendel',
 'mendeleev',
 'meninsky',
 'merkle',
 'mestorf',
 'mirzakhani',
 'montalcini',
 'moore',
 'morse',
 'moser',
 'murdock',
 'napier',
 'nash',
 'neumann',
 'newton',
 'nightingale',
 'nobel',
 'noether',
 'northcutt',
 'noyce',
 'panini',
 'pare',
 'pascal',
 'pasteur',
 'payne',
 'perlman',
 'pike',
 'poincare',
 'poitras',
 'proskuriakova',
 'ptolemy',
 'raman',
 'ramanujan',
 'rhodes',
 'ride',
 'ritchie',
 'robinson',
 'roentgen',
 'rosalind',
 'rubin',
 'saha',
 'sammet',
 'sanderson',
 'satoshi',
 'shamir',
 'shannon',
 'shaw',
 'shirley',
 'shockley',
 'shtern',
 'sinoussi',
 'snyder',
 'solomon',
 'spence',
 'stonebraker',
 'sutherland',
 'swanson',
 'swartz',
 'swirles',
 'taussig',
 'tesla',
 'tharp',
 'thompson',
 'torvalds',
 'tu',
 'turing',
 'varahamihira',
 'vaughan',
 'villani',
 'visvesvaraya',
 'volhard',
 'wescoff',
 'wilbur',
 'wiles',
 'williams',
 'williamson',
 'wilson',
 'wing',
 'wozniak',
 'wright',
 'wu',
 'yalow',
 'yonath',
 'zhukovsky']

# Tuples defining the inclusive ranges for the major-minor-patch version numbering.
VERSION_RANGE = ((0, 3), (0, 9), (0, 14))

# The number of packages to generate.
PACKAGES = 10

if __name__ == "__main__":
    # Invoke the bundle script to generate the /build directory and 
    # pygin-build.zip in this directory.
    
    # Unzip pygin-build.zip to a temporary directory.
    
    # Generate our new package name/version number.
    
    # Open the agent definition file and look for the name and version string,
    # then use regex replace.
    
    # Write agent.py back.
    
    # Rezip that folder, copy out.
    
    # Rinse and repeat until done.
    