# This dockerfile is intended to be used in payload generation.

FROM python:3.11.4-bookworm

WORKDIR /app

# Don't use .pyc files.
ENV PYTHONDONTWRITEBYTECODE 1
# Send stdout to terminal without buffering.
ENV PYTHONUNBUFFERED 1
# Yes I'm fine with allowing unsafe pickling
ENV C_FORCE_ROOT 1

# Install Firefox (dddb)
COPY ./resources ./resources
RUN chmod +x ./resources/runtime/install-firefox.sh
RUN ./resources/runtime/install-firefox.sh

# Install Python packages
RUN pip3 install --upgrade pip
COPY requirements.txt ./
RUN pip3 install -r requirements.txt -U

# Everything else
COPY . .

# Assert that build_config.json is copied over, if cached from the previous step
COPY build_config.[json] ./

# Execute the main script. Right now, all this does is overwrite agent_cfg.json
# with the final configuration that the agent will actually run on, but
# in theory you could get this to run PyInstaller.
CMD make payload