# Should be called from within the main container.
# There's only one container right now, but in theory you might need multiple
# for an agent to build if they have disparate platforms for one payload.
services:
  pygin_message:
    container_name: pygin_message
    build:
      context: .
      dockerfile: Dockerfile.messaging
    command: make message