# This dockerfile is intended to be used in messaging.

FROM unrdeaddrop/pygin:DOES_NOT_EXIST

WORKDIR /app

# Assert that build_config.json is copied over, if cached from the previous step
COPY build_config.json .

# Execute the main script. Right now, all this does is overwrite agent_cfg.json
# with the final configuration that the agent will actually run on, but
# in theory you could get this to run PyInstaller.
CMD make payload