name: Generate DeadDrop package

on:
  push:
    tags:
      - "v*.*.*"

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate package
        run: ./bundle.sh
      
      - name: Get Pygin version
        id: meta
        run: |
          echo "version=$(python3 -m src.meta.agent)" >> $GITHUB_OUTPUT
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pygin-build-${{ steps.meta.outputs.version }}.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}